### ISSUE TITLE
Add missing List Views to K12 Kit

### ISSUE THREAD

**Issue by lifewithryan** [SalesforceFoundation/k12-architecture-kit#141]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
- Feature
* **What is the current behavior?**
- a few objects don't have list views configured for K12 Kit
* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
- Increase usability
* **Acceptance Criteria**
-  Attribute (K-12 All Student Characteristics; K-12 All Credentials)
- Grade Enrollment (K-12 All Grade Enrollments)
- Languages (K-12 All Languages)
- Relationships (K-12 All Relationships)

**Comment by lifewithryan** [comment]
**lurch: attach W-037841

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HpKwQAK" target="_blank">W-037841</a>
