### ISSUE TITLE
Add K12 App tile to App Launcher when installing from the installer link

### ISSUE THREAD

**Issue by lifewithryan** [SalesforceFoundation/k12-architecture-kit#142]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
- Bug
* **What is the current behavior?**
- after installing K12 Architecture Kit via the installer link, I have to manually give the Admin profile access to the app
* **What is the expected behavior?**
- I should have access to the app by default after running the installer
* **What is the motivation / use case for changing the behavior?**
- it seems counter intuitive to the customer to install K12 Kit and not have access to the app tile be default
* **Acceptance Criteria**
- after running the installer, I should be able to see the K12 Architecture Kit app tile from the App Launcher

**Comment by lifewithryan** [comment]
**lurch: attach W-037541

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoisQAC" target="_blank">W-037541</a>
