### ISSUE TITLE
[K12] Updates to Grade Enrollment Picklists

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/k12-architecture-kit#154]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
feature
* **What is the current behavior?**
The current picklist values for Entry Reason, Exit Reason, and Status are not in order. 
There is no "Other" picklist values for the 3 picklist fields. 
* **What is the expected behavior?**
We need to provide "Other" as an option for Entry Reason and Exit Reason and sort them in alphabetical order and leave Other as the last value. 
We need to only have the values "Current" and "Former" for the Status picklist field. 
* **What is the motivation / use case for changing the behavior?**
Data integrity 
* **Acceptance Criteria**
*Acceptance Criteria 1:*
Given: A grade enrollment record
When: I view the options for Status
Then: I should only see Current and Former

*User Story 2*
As a: school administrator
I want to: be able to set the Exit Reason on Grade Enrollment to “Other”
So that: I can track when a student has exited a grade as graduated.

*Acceptance Criteria 2:*
Given: A grade enrollment record
When: I view the options for Exit Reason
Then: I should be able to select “Graduated”

*User Story 3*
As a: school administrator
I want to: be able to set the Exit Reason on Grade Enrollment to “Completed”
So that: I can track when a student has exited a grade as completed.

*Acceptance Criteria 3:*
Given: A grade enrollment record
When: I view the options for Exit Reason
Then: I should be able to select “Completed

**Comment by kdy618** [comment]
**lurch: attach W-038367

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqDxQAK" target="_blank">W-038367</a>
