### ISSUE TITLE
k12: Handle Deletion of Grade Enrollments

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/k12-architecture-kit#169]
ENHANCEMENT REQUEST

What is the current behavior?

When all of a Contact's Grade Enrollments have been deleted the "Current Grade Level" field on Contact Details still shows whichever Grade Level was last marked as Contact.

What is the expected behavior?

When a Contact has no Grade Enrollment Records marked as "Current", the Current Grade Level field on Contact should be changed to 'Not Applicable'.

Steps:

Create Contact, Name = Marcus Jefferson
Create Multiple Grade Enrollment Records, with Grade Level & Status :
--> First Grade, Former
--> Second Grade, Former
--> Third Grade, Current
Note that the "Current Grade Level" on the Contact Details now says "Third Grade."
Delete the Third Grade, Current Grade Enrollment 
--> Actual Result : Marcus's "Current Grade Level" still says "Third Grade"
--> Expected Result : Marcus's "Current Grade Level" is blank, since he is not currently in that school. (Alternatively, says "N/A".)
What is the motivation / use case for changing the behavior?

So that school personal can accurately use the Contact Details to know if a student is enrolled in a grade at their school
Keeping Data in Sync
Less work trying to maintain data in 2 places
Acceptance Criteria

Given: A Contact with Grade Enrollment Records
When: None are marked "Current"
Then: The "Current Grade Level" field on that Contact's details now changed to 'Not Applicable'.

**Comment by skosgi1** [comment]
**lurch: attach W-038901

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hr8QQAS" target="_blank">W-038901</a>
