### ISSUE TITLE
K12 Update the Exit Reason picklist value to "No-Show" on Grade Enrollment

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/k12-architecture-kit#173]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
bug 
* **What is the current behavior?**
"No Show" is currently the format for Exit Reason's picklist value. 
* **What is the expected behavior?**
"No-Show" is the expected format for Exist Reason's picklist value. 
* **What is the motivation / use case for changing the behavior?**
data integrity.

**Comment by kdy618** [comment]
**lurch: attach W-039472

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsJjQAK" target="_blank">W-039472</a>
