### ISSUE TITLE
[K12] Adding  All Application List View and Page Layout

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/k12-architecture-kit#174]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
feature
* **What is the current behavior?**
Application object's page layout is defaulted to EDA
* **What is the expected behavior?**
Application object's page layout should be defaulted to a K12 version 
* **What is the motivation / use case for changing the behavior?**
data integrity

**Comment by kdy618** [comment]
**lurch: attach W-038892

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hr6wQAC" target="_blank">W-038892</a>
