### ISSUE TITLE
[K-12] Tracking School Days Missed on Behavior Response

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/k12-architecture-kit#184]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Behavior response doesn't have a 'Days Missed' field.

* **What is the expected behavior?**
Behavior response should have a 'Days Missed' field.

* **What is the motivation / use case for changing the behavior?**
To track number of days missed

* **Acceptance Criteria**

Behavior response should have a 'Days Missed' field.

**Comment by skosgi1** [comment]
**lurch: attach W-040181

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtcRQAS" target="_blank">W-040181</a>
