### ISSUE TITLE
[K12] Picklist Updates to Case(Behavior Involvement) and Behavior Response Objects

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/k12-architecture-kit#198]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature 
* **What is the current behavior?**
As a school administrator, I cannot record response to an incident that involved one or more of my students either at school or not so that I can record and track behavior and the responses taken by my school. 

As a school administrator I cannot record where an incident occurred so that I can better track problem areas at my school.

* **What is the expected behavior?**
As a school administrator I can record the response to an incident that involved one or more of my students either at school or not so that I can record and track behavior and the responses taken by my school.

As a school administrator I can record where an incident occurred so that I can better track problem areas at my school.

* **What is the motivation / use case for changing the behavior?**
Data Integrity

**Comment by kdy618** [comment]
**lurch: attach W-034553

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7qqQAC" target="_blank">W-034553</a>
