### ISSUE TITLE
[K-12] Recording a Positive Behavior Response on Behavior Response Object

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/k12-architecture-kit#204]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
Currently, schools do not have a way to record positive behaviors. 
* **What is the expected behavior?**
As a school administrator I can record a Positive Behavior Response the school had to a student for a Positive Behavior Case so that I can positively impact school culture.
* **What is the motivation / use case for changing the behavior?**
Data Integrity
* **Acceptance Criteria**
1. I can relate the Positive Behavior Involvement this Response is to
2. I can optionally write a description
    1. current functionality on Behavior Response
3. I can select a Type of positive response
    1. Values
        1. Award
        2. Verbal Recognition
        3. Other
    2. Required
        1. current functionality on Behavior Response
4. I can optionally record a Status
    1. Current functionality
5. I can optionally record a start date
    1. current functionality on Behavior Response
6. I can optionally record an end date
    1. current functionality on Behavior Response

**Comment by kdy618** [comment]
**lurch: attach W-040060

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtNiQAK" target="_blank">W-040060</a>
